.PHONY: \
default \
clean \
test_algorithm \
test_cmath \
test_concept \
test_deducing_this \
test_float \
test_float_exception \
test_initializer_lists \
test_multidimensional_subscript_operator \
test_static_lambda \
test_std_is_base_of \
test_std_conditional \
test_structured_bindings \
test_three_way_comparison \
test_type_traits \
test_utility

CC = g++
CPP_FLAGS = -g -Wall -std=c++23

default: test_algorithm

clean:
	rm -rf ./bin

test_algorithm:
	mkdir -p bin/
	$(CC) $(CPP_FLAGS) $@.cc -o bin/$@
	./bin/$@

test_cmath:
	mkdir -p bin/
	$(CC) $(CPP_FLAGS) $@.cc -o bin/$@
	./bin/$@

test_concept:
	mkdir -p bin/
	$(CC) $(CPP_FLAGS) $@.cc -o bin/$@
	./bin/$@

test_deducing_this:
	mkdir -p bin/
	$(CC) $(CPP_FLAGS) $@.cc -o bin/$@
	./bin/$@

test_float:
	mkdir -p bin/
	$(CC) $(CPP_FLAGS) $@.cc -o bin/$@
	./bin/$@

test_float_exception:
	mkdir -p bin/
	$(CC) $(CPP_FLAGS) $@.cc -o bin/$@
	./bin/$@

test_initializer_lists:
	mkdir -p bin/
	$(CC) $(CPP_FLAGS) $@.cc -o bin/$@
	./bin/$@

test_multidimensional_subscript_operator:
	mkdir -p bin/
	$(CC) $(CPP_FLAGS) $@.cc -o bin/$@
	./bin/$@

test_static_lambda:
	mkdir -p bin/
	$(CC) $(CPP_FLAGS) $@.cc -o bin/$@
	./bin/$@

test_std_is_base_of:
	mkdir -p bin/
	$(CC) $(CPP_FLAGS) $@.cc -o bin/$@
	./bin/$@

test_std_conditional:
	mkdir -p bin/
	$(CC) $(CPP_FLAGS) $@.cc -o bin/$@
	./bin/$@

test_structured_bindings:
	mkdir -p bin/
	$(CC) $(CPP_FLAGS) $@.cc -o bin/$@
	./bin/$@

test_three_way_comparison:
	mkdir -p bin/
	$(CC) $(CPP_FLAGS) $@.cc -o bin/$@
	./bin/$@

test_type_traits:
	mkdir -p bin/
	$(CC) $(CPP_FLAGS) $@.cc -o bin/$@
	./bin/$@

test_utility:
	mkdir -p bin/
	$(CC) $(CPP_FLAGS) $@.cc -o bin/$@
	./bin/$@
